$(document).ready(function() {
    $('#result-table').DataTable( {
        "paging":    false,
        "ordering":  false,
        "info":      false,
        "autoWidth": false,
        "searching": false
    } );
} );